# Remap prefix
# export TERM=screen-256color

# Prevent escape from acting as meta 
set -sg escape-time 0
set-option -g default-terminal "tmux-256color"
set-option -g default-shell /bin/zsh
set -g focus-events on

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind - split-window -v
bind _ split-window -v -c "#{pane_current_path}"
bind \\ split-window -h
bind | split-window -h -c "#{pane_current_path}"

bind g new-window -c "#{pane_current_path}" "$HOME/.local/bin/lazygit"
bind r source-file ~/.tmux.conf

unbind E
bind v send-keys "~/dotfiles/tmux-scripts/start-vim.sh" Enter
bind d send-keys '~/dotfiles/tmux-scripts/tmux-dev.sh' Enter
# bind t send-keys "~/dotfiles/tmux-scripts/tmux-dev.sh '/tmp'" Enter
# bind h run-shell -b "$HOME/dotfiles/tmux-scripts/open-dotfiles.sh"

bind-key -T copy-mode e send-keys -X copy-line-and-cancel \; send-keys "~/dotfiles/tmux-scripts/open-file-vim.sh" Enter

# bind e run '~/dotfiles/tmux-scripts/open-file-vim.sh'
# bind e send-keys -X copy-pipe-and-cancel "cat > /tmp/copied-line.txt"

bind e run '~/dotfiles/tmux-scripts/open-file-vim.sh'


# Hotkeys
#-------------------------------------------------------#
unbind o
bind o select-layout -o

bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D
#
bind -r C-h resize-pane -L 8
bind -r C-j resize-pane -D 2
bind -r C-k resize-pane -U 2
bind -r C-l resize-pane -R 8
#
# bind -r C-h swap-pane -L
# bind -r C-l swap-pane -R
# bind -r C-j swap-pane -D
# bind -r C-k swap-pane -U
#
#
# Plugins
#-------------------------------------------------------#
set -g @plugin 'tmux-plugins/tpm'  
set -g @plugin 'erikw/tmux-powerline'
run '~/.tmux/plugins/tpm/tpm'





# Pane colours
#-------------------------------------------------------#
# set inactive/active window styles
set -g window-style 'fg=colour247,bg=black'
set -g window-active-style 'fg=colour250,bg=#282828'

