# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$HOME/.oh-my-zsh"
export ANEMOI_BASE_SEED=1


# Setup Pyenv
# -----------
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)" # Lets us call pyenv shell python


# Add path to NVIM v.10
# ---------------------
export PATH="$HOME/src/nvim-linux64/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"


# Setup Flutter SDK
export PATH="$HOME/opt/flutter/bin:$PATH"

# Setup custom aliases
# --------------------
alias activate='source venv/bin/activate'
alias new-venv="source $HOME/dotfiles/scripts/new-venv.sh"


# Setup Plugins for zsh
# ---------------------
ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(
	git
    fzf
    zsh-autosuggestions
    zsh-syntax-highlighting # must stay last in this list
)
source $ZSH/oh-my-zsh.sh

# Prompt, fuzzy cd, and nicer ls/cat
# -----------------------------------
# eval "$(starship init zsh)" # swapped for powerlevel10k, re-enable to go back
eval "$(zoxide init zsh)"
alias cat='bat'


# eval "$(fzf --zsh)"
bindkey '^R' fzf-history-widget


lsd() {
  if [ "$#" -eq 0 ]; then
    /bin/ls -d "$PWD"/*
  else
    /bin/ls -d "$PWD"/$1/*
  fi
}


__conda_setup="$('/Users/jacobsch/mambaforge/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/jacobsch/mambaforge/etc/profile.d/conda.sh" ]; then
        . "/Users/jacobsch/mambaforge/etc/profile.d/conda.sh"
    else
        export PATH="/Users/jacobsch/mambaforge/bin:$PATH"
    fi
fi
unset __conda_setup

if [ -f "/Users/jacobsch/mambaforge/etc/profile.d/mamba.sh" ]; then
    . "/Users/jacobsch/mambaforge/etc/profile.d/mamba.sh"
fi
# <<< conda initialize <<<


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Allow MLflow's deprecated filesystem tracking store (used for local/offline anemoi-training runs)
export MLFLOW_ALLOW_FILE_STORE=true

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
